In [14]:
import pandas as pd

raw_data=pd.read_html("https://www.moneycontrol.com/stocks/marketstats/industry-classification/bse/abrasives.html")

df_bse_abrasives = raw_data[0] #list to dataframe

#df_abrasives_bse = df_abrasives_bse.drop(columns=['Unnamed: 9','Unnamed: 10','Unnamed: 11','Unnamed: 12','Unnamed: 13','Unnamed: 14','Unnamed: 15','Unnamed: 16','Unnamed: 17','Unnamed: 18','Unnamed: 19'],axis=1)

df_bse_abrasives[['Company','others']]= df_bse_abrasives['Company Name'].str.split(r"\bAdd\b",expand=True)
df_bse_abrasives['Company Name']=df_bse_abrasives['Company']

#https://pandas.pydata.org/pandas-docs/stable/getting_started/10min.html > selection by position
#https://stackoverflow.com/questions/55291667/getting-typeerror-slicenone-none-none-0-is-an-invalid-key
df_bse_abrasives = df_bse_abrasives.iloc[ ::7 , :6: ]

df_bse_abrasives

         Company Name     Open     High      Low  Last Price  Prev Price
0       Carborundum     206.00   210.65   194.95       196.9       195.9
7   Grindwell Norto     451.35   452.00   440.00       452.0       439.3
14            Wendt    1723.05  1768.75  1696.30      1710.0      1724.0

In [23]:
raw_data=pd.read_html("https://www.moneycontrol.com/stocks/marketstats/industry-classification/nse/abrasives.html")

df_nse_abrasives = raw_data[0]

df_nse_abrasives[['Company','others']]= df_nse_abrasives['Company Name'].str.split(r"\bAdd\b",expand=True)
df_nse_abrasives['Company Name']=df_nse_abrasives['Company']

df_nse_abrasives= df_nse_abrasives.iloc[ ::7, :6:]

df_nse_abrasives

         Company Name     Open     High      Low  Last Price  Prev Price
0       Carborundum     201.30   209.95   190.10       195.6      194.80
7   Grindwell Norto     435.00   454.45   431.05       452.0      441.20
14            Wendt    1750.05  1750.05  1631.65      1750.0     1703.35

In [24]:
import pandas as pd

raw_data = pd.read_html("https://www.moneycontrol.com/stocks/marketstats/industry-classification/bse/aerospace-defence.html")

df_bse_aerospace_defence = raw_data[0]

df_bse_aerospace_defence[['Company','others']]= df_bse_aerospace_defence['Company Name'].str.split(r"\bAdd\b",expand=True)
df_bse_aerospace_defence['Company Name']=df_bse_aerospace_defence['Company']

df_bse_aerospace_defence = df_bse_aerospace_defence.iloc[ ::7, :6:]

df_bse_aerospace_defence

         Company Name    Open    High    Low  Last Price  Prev Price
0   Hindustan Aeron    483.50  505.40  472.9      500.10      482.35
7   TAAL Enterprise    108.00  109.95   92.0      105.00      100.05
14  Taneja Aerospac     14.00   14.50   13.5       14.15       13.50

In [29]:
raw_data = pd.read_html("https://www.moneycontrol.com/stocks/marketstats/industry-classification/nse/aerospace-defence.html")

raw_data

df_nse_aerospace_defence = raw_data[0]

df_nse_aerospace_defence[['Company','others']]= df_nse_aerospace_defence['Company Name'].str.split(r"\bAdd\b",expand=True)
df_nse_aerospace_defence['Company Name']=df_nse_aerospace_defence['Company']

df_nse_aerospace_defence = df_nse_aerospace_defence.iloc[ ::7 , :6:]

df_nse_aerospace_defence

        Company Name    Open   High    Low  Last Price  Prev Price
0  Hindustan Aeron    485.00  502.4  478.5      497.95       479.5

In [30]:
raw_data = pd.read_html("https://www.moneycontrol.com/stocks/marketstats/industry-classification/bse/agriculture.html")

raw_data

df_bse_agriculture = raw_data[0]

df_bse_agriculture[['Company','others']]= df_bse_agriculture['Company Name'].str.split(r"\bAdd\b",expand=True)
df_bse_agriculture['Company Name']=df_bse_agriculture['Company']

df_bse_agriculture = df_bse_agriculture.iloc[ ::7 , :7:]

df_bse_agriculture

         Company Name    Open    High     Low  Last Price  Prev Price  Change
0         Agri-Tech     17.15   17.15   17.15       17.15       17.00    0.15
7    Beeyu Overseas      0.33    0.33    0.33        0.33        0.33    0.00
14    Bombay Burmah    650.00  711.20  636.90      700.00      646.55   53.45
21     Dhunseri Tea    100.00  128.00  100.00      128.00      107.00   21.00
28        Diana Tea      6.69    6.69    5.67        6.23        6.69   -0.46
35  Goodricke Group     95.85  102.00   95.85       99.80       95.85    3.95
42  Harrisons Malay     50.00   53.00   50.00       50.25       50.45   -0.20
49  Indo US Bio-Tec     52.75   53.50   51.25       51.50       53.00   -1.50
56  JK Agri Genetic    301.00  334.00  301.00      329.00      306.20   22.80
63        Kanel Ind      0.30    0.30    0.30        0.30        0.31   -0.01
70      Kaveri Seed    317.90  338.00  317.90      327.55      322.50    5.05
77   Mangalam Seeds     54.90   54.90   54.90       54.90       55.00   -0.10
84   Nath Bio-Genes    131.80  145.60  131.80      142.00      138.70    3.30

In [0]:
raw_data = pd.read_html("https://www.moneycontrol.com/stocks/marketstats/industry-classification/nse/agriculture.html")

raw_data

df_nse_agriculture = raw_data[0]

df_nse_agriculture = df_nse_agriculture.drop(columns=['Unnamed: 9','Unnamed: 10','Unnamed: 11','Unnamed: 12','Unnamed: 13','Unnamed: 14','Unnamed: 15','Unnamed: 16','Unnamed: 17','Unnamed: 18','Unnamed: 19'],axis=1)

df_nse_agriculture = df_nse_agriculture[0::7][:7:]

df_nse_agriculture

                                         Company Name  ... 5 Day Performance  5 Day Performance  Volume  Lower Circuit  Upper Circuit  VWAP  SMA 30 DMA  50 DMA  150 DMA  200 DMA  Deliverables  P/E  P/B
0   Agri-Tech  Add to  Watchlist | Portfolio ACTIO...  ...  AVERAGE VOLUME  5-Day  17279.80  10-Day  5312....
7   Bombay Burmah  Add to  Watchlist | Portfolio A...  ...  AVERAGE VOLUME  5-Day  74601.60  10-Day  4902....
14  Bombay Super  Add to  Watchlist | Portfolio AC...  ...  AVERAGE VOLUME  5-Day  1200.00  10-Day  30-Day...
21  Dhunseri Tea  Add to  Watchlist | Portfolio AC...  ...  AVERAGE VOLUME  5-Day  1831.60  10-Day  195.90...
28  Harrisons Malay  Add to  Watchlist | Portfolio...  ...  AVERAGE VOLUME  5-Day  23060.40  10-Day  5434....
35  Kaveri Seed  Add to  Watchlist | Portfolio ACT...  ...  AVERAGE VOLUME  5-Day  116111.80  10-Day  1671...
42  Nath Bio-Genes  Add to  Watchlist | Portfolio ...  ...  AVERAGE VOLUME  5-Day  28606.60  10-Day  16761...

[7 rows x 9 columns]

In [0]:
raw_data = pd.read_html("https://www.moneycontrol.com/stocks/marketstats/industry-classification/bse/air-conditioners.html")

raw_data

df_bse_air_conditioners = raw_data[0]

df_bse_air_conditioners = df_bse_air_conditioners.drop(columns=['Unnamed: 9','Unnamed: 10','Unnamed: 11','Unnamed: 12','Unnamed: 13','Unnamed: 14','Unnamed: 15','Unnamed: 16','Unnamed: 17','Unnamed: 18','Unnamed: 19'],axis=1)

df_bse_air_conditioners = df_bse_air_conditioners[0::7][:7:]

df_bse_air_conditioners

                                         Company Name  ... 5 Day Performance  5 Day Performance  Volume  Lower Circuit  Upper Circuit  VWAP  SMA 30 DMA  50 DMA  150 DMA  200 DMA  Deliverables  P/E  P/B
0   Amber Enterpris  Add to  Watchlist | Portfolio...  ...  AVERAGE VOLUME  5-Day  6771.40  10-Day  6043.1...
7   Blue Star  Add to  Watchlist | Portfolio NEWS ...  ...  AVERAGE VOLUME  5-Day  2507.60  10-Day  4485.8...
14  Johnson Control  Add to  Watchlist | Portfolio...  ...  AVERAGE VOLUME  5-Day  4798.60  10-Day  4008.2...
21  Voltas  Add to  Watchlist | Portfolio ACTIONS ...  ...  AVERAGE VOLUME  5-Day  51975.20  10-Day  54407...

[4 rows x 9 columns]

In [0]:
raw_data = pd.read_html("https://www.moneycontrol.com/stocks/marketstats/industry-classification/nse/air-conditioners.html")

raw_data

df_nse_air_conditioners = raw_data[0]

df_nse_air_conditioners = df_nse_air_conditioners.drop(columns=['Unnamed: 9','Unnamed: 10','Unnamed: 11','Unnamed: 12','Unnamed: 13','Unnamed: 14','Unnamed: 15','Unnamed: 16','Unnamed: 17','Unnamed: 18','Unnamed: 19'],axis=1)

df_nse_air_conditioners = df_nse_air_conditioners[0::7][:7:]

df_nse_air_conditioners

                                         Company Name  ... 5 Day Performance  5 Day Performance  Volume  Lower Circuit  Upper Circuit  VWAP  SMA 30 DMA  50 DMA  150 DMA  200 DMA  Deliverables  P/E  P/B
0   Amber Enterpris  Add to  Watchlist | Portfolio...  ...  AVERAGE VOLUME  5-Day  121165.00  10-Day  6043...
7   Blue Star  Add to  Watchlist | Portfolio NEWS ...  ...  AVERAGE VOLUME  5-Day  68258.40  10-Day  4485....
14  ICE Make Refrig  Add to  Watchlist | Portfolio...  ...  AVERAGE VOLUME  5-Day  15600.00  10-Day  30-Da...
21  Johnson Control  Add to  Watchlist | Portfolio...  ...  AVERAGE VOLUME  5-Day  16907.00  10-Day  4008....
28  Voltas  Add to  Watchlist | Portfolio ACTIONS ...  ...  AVERAGE VOLUME  5-Day  1818382.80  10-Day  544...

[5 rows x 9 columns]

In [0]:
raw_data = pd.read_html("https://www.moneycontrol.com/stocks/marketstats/industry-classification/bse/airlines.html")

raw_data

df_bse_airline = raw_data[0]

df_bse_airline = df_bse_airline.drop(columns=['Unnamed: 9','Unnamed: 10','Unnamed: 11','Unnamed: 12','Unnamed: 13','Unnamed: 14','Unnamed: 15','Unnamed: 16','Unnamed: 17','Unnamed: 18','Unnamed: 19'],axis=1)

df_bse_airline = df_bse_airline[0::7][:7:]

df_bse_airline

                                         Company Name  ... 5 Day Performance  5 Day Performance  Volume  Lower Circuit  Upper Circuit  VWAP  SMA 30 DMA  50 DMA  150 DMA  200 DMA  Deliverables  P/E  P/B
0   Global Vectra  Add to  Watchlist | Portfolio A...  ...  AVERAGE VOLUME  5-Day  2630.80  10-Day  6924.2...
7   Interglobe Avi  Add to  Watchlist | Portfolio ...  ...  AVERAGE VOLUME  5-Day  106128.00  10-Day  1121...
14  Jet Airways  Add to  Watchlist | Portfolio NEW...  ...  AVERAGE VOLUME  5-Day  6755.00  10-Day  15425....
21  SpiceJet  Add to  Watchlist | Portfolio ACTION...  ...  AVERAGE VOLUME  5-Day  2095785.00  10-Day  178...

[4 rows x 9 columns]

In [0]:
raw_data = pd.read_html("https://www.moneycontrol.com/stocks/marketstats/industry-classification/nse/airlines.html")

raw_data

df_nse_airline = raw_data[0]

df_nse_airline = df_nse_airline.drop(columns=['Unnamed: 9','Unnamed: 10','Unnamed: 11','Unnamed: 12','Unnamed: 13','Unnamed: 14','Unnamed: 15','Unnamed: 16','Unnamed: 17','Unnamed: 18','Unnamed: 19'],axis=1)

df_nse_airline = df_nse_airline[0::7][:7:]

df_nse_airline

                                         Company Name  ... 5 Day Performance  5 Day Performance  Volume  Lower Circuit  Upper Circuit  VWAP  SMA 30 DMA  50 DMA  150 DMA  200 DMA  Deliverables  P/E  P/B
0   Global Vectra  Add to  Watchlist | Portfolio A...  ...  AVERAGE VOLUME  5-Day  13832.60  10-Day  6924....
7   Interglobe Avi  Add to  Watchlist | Portfolio ...  ...  AVERAGE VOLUME  5-Day  2461206.20  10-Day  112...
14  Jet Airways  Add to  Watchlist | Portfolio NEW...  ...  AVERAGE VOLUME  5-Day  46248.80  10-Day  15425...
21  SpiceJet  Add to  Watchlist | Portfolio ACTION...  ...  AVERAGE VOLUME  5-Day  6321052.80  10-Day  178...

[4 rows x 9 columns]

In [0]:
raw_data = pd.read_html("https://www.moneycontrol.com/stocks/marketstats/industry-classification/bse/aluminium-aluminium-products.html")

raw_data

df_bse_aluminium = raw_data[0]

df_bse_aluminium = df_bse_aluminium.drop(columns=['Unnamed: 9','Unnamed: 10','Unnamed: 11','Unnamed: 12','Unnamed: 13','Unnamed: 14','Unnamed: 15','Unnamed: 16','Unnamed: 17','Unnamed: 18','Unnamed: 19'],axis=1)

df_bse_aluminium = df_bse_aluminium[0::7][:7:]

df_bse_aluminium

                                         Company Name  ... 5 Day Performance  5 Day Performance  Volume  Lower Circuit  Upper Circuit  VWAP  SMA 30 DMA  50 DMA  150 DMA  200 DMA  Deliverables  P/E  P/B
0   Arfin India  Add to  Watchlist | Portfolio ACT...  ...  AVERAGE VOLUME  5-Day  5479.80  10-Day  3469.1...
7   Century Extr  Add to  Watchlist | Portfolio AN...  ...  AVERAGE VOLUME  5-Day  15970.00  10-Day  13978...
14  Hind Aluminium  Add to  Watchlist | Portfolio ...  ...  AVERAGE VOLUME  5-Day  1042.20  10-Day  1365.1...
21  Maan Aluminium  Add to  Watchlist | Portfolio ...  ...  AVERAGE VOLUME  5-Day  1175.60  10-Day  854.10...
28  Manaksia Alumin  Add to  Watchlist | Portfolio...  ...  AVERAGE VOLUME  5-Day  1481.00  10-Day  2243.7...
35  NALCO  Add to  Watchlist | Portfolio ACTIONS  ...  ...  AVERAGE VOLUME  5-Day  1333578.40  10-Day  857...
42  PG Foils  Add to  Watchlist | Portfolio ACTION...  ...  AVERAGE VOLUME  5-Day  1692.80  10-Day  1244.5...

[7 rows x 9 columns]

In [0]:
raw_data = pd.read_html("https://www.moneycontrol.com/stocks/marketstats/industry-classification/nse/aluminium-aluminium-products.html")

raw_data

df_nse_aluminium = raw_data[0]

df_nse_aluminium = df_nse_aluminium.drop(columns=['Unnamed: 9','Unnamed: 10','Unnamed: 11','Unnamed: 12','Unnamed: 13','Unnamed: 14','Unnamed: 15','Unnamed: 16','Unnamed: 17','Unnamed: 18','Unnamed: 19'],axis=1)

df_nse_aluminium = df_nse_aluminium[0::7][:7:]

df_nse_aluminium

                                         Company Name  ... 5 Day Performance  5 Day Performance  Volume  Lower Circuit  Upper Circuit  VWAP  SMA 30 DMA  50 DMA  150 DMA  200 DMA  Deliverables  P/E  P/B
0   Century Extr  Add to  Watchlist | Portfolio AN...  ...  AVERAGE VOLUME  5-Day  117579.20  10-Day  1397...
7   Maan Aluminium  Add to  Watchlist | Portfolio ...  ...  AVERAGE VOLUME  5-Day  10101.60  10-Day  854.1...
14  Manaksia Alumin  Add to  Watchlist | Portfolio...  ...  AVERAGE VOLUME  5-Day  11903.20  10-Day  2243....
21  NALCO  Add to  Watchlist | Portfolio ACTIONS  ...  ...  AVERAGE VOLUME  5-Day  12948280.00  10-Day  85...

[4 rows x 9 columns]

In [0]:
raw_data = pd.read_html("https://www.moneycontrol.com/stocks/marketstats/industry-classification/bse/amusement-parksrecreationclub.html")

raw_data

df_bse_amusement_parksrecreationclub = raw_data[0]

df_bse_amusement_parksrecreationclub = df_bse_amusement_parksrecreationclub.drop(columns=['Unnamed: 9','Unnamed: 10','Unnamed: 11','Unnamed: 12','Unnamed: 13','Unnamed: 14','Unnamed: 15','Unnamed: 16','Unnamed: 17','Unnamed: 18','Unnamed: 19'],axis=1)

df_bse_amusement_parksrecreationclub = df_bse_amusement_parksrecreationclub[0::7][:7:]

df_bse_amusement_parksrecreationclub

                                        Company Name  ... 5 Day Performance  5 Day Performance  Volume  Lower Circuit  Upper Circuit  VWAP  SMA 30 DMA  50 DMA  150 DMA  200 DMA  Deliverables  P/E  P/B
0  Nicco Parks  Add to  Watchlist | Portfolio ACT...  ...  AVERAGE VOLUME  5-Day  72448.80  10-Day  40741...
7  Wonderla  Add to  Watchlist | Portfolio NEWS  ...  ...  AVERAGE VOLUME  5-Day  1958.60  10-Day  1507.7...

[2 rows x 9 columns]

In [0]:
raw_data = pd.read_html("https://www.moneycontrol.com/stocks/marketstats/industry-classification/nse/amusement-parksrecreationclub.html")

raw_data

df_nse_amusement_parksrecreationclub = raw_data[0]

df_nse_amusement_parksrecreationclub = df_nse_amusement_parksrecreationclub.drop(columns=['Unnamed: 9','Unnamed: 10','Unnamed: 11','Unnamed: 12','Unnamed: 13','Unnamed: 14','Unnamed: 15','Unnamed: 16','Unnamed: 17','Unnamed: 18','Unnamed: 19'],axis=1)

df_nse_amusement_parksrecreationclub = df_nse_amusement_parksrecreationclub[0::7][:7:]

df_nse_amusement_parksrecreationclub

                                        Company Name  ... 5 Day Performance  5 Day Performance  Volume  Lower Circuit  Upper Circuit  VWAP  SMA 30 DMA  50 DMA  150 DMA  200 DMA  Deliverables  P/E  P/B
0  Wonderla  Add to  Watchlist | Portfolio NEWS  ...  ...  AVERAGE VOLUME  5-Day  69233.40  10-Day  1507....

[1 rows x 9 columns]

In [0]:
raw_data = pd.read_html("https://www.moneycontrol.com/stocks/marketstats/industry-classification/bse/aquaculture.html")

raw_data

df_bse_aquaculture = raw_data[0]

df_bse_aquaculture = df_bse_aquaculture.drop(columns=['Unnamed: 9','Unnamed: 10','Unnamed: 11','Unnamed: 12','Unnamed: 13','Unnamed: 14','Unnamed: 15','Unnamed: 16','Unnamed: 17','Unnamed: 18','Unnamed: 19'],axis=1)

df_bse_aquaculture = df_bse_aquaculture[0::7][:7:]

df_bse_aquaculture

                                         Company Name  ... 5 Day Performance  5 Day Performance  Volume  Lower Circuit  Upper Circuit  VWAP  SMA 30 DMA  50 DMA  150 DMA  200 DMA  Deliverables  P/E  P/B
0   Apex Frozen  Add to  Watchlist | Portfolio ACT...  ...  AVERAGE VOLUME  5-Day  52876.40  10-Day  36650...
7   Avanti Feeds  Add to  Watchlist | Portfolio AC...  ...  AVERAGE VOLUME  5-Day  102055.80  10-Day  8236...
14  Coastal Corp  Add to  Watchlist | Portfolio AN...  ...  AVERAGE VOLUME  5-Day  1673.00  10-Day  1359.3...
21  Waterbase  Add to  Watchlist | Portfolio ACTIO...  ...  AVERAGE VOLUME  5-Day  54617.00  10-Day  47368...
28  Zeal Aqua Add to  Watchlist | Portfolio ANNOUN...  ...        AVERAGE VOLUME  5-Day  10-Day  30-Day  1008

[5 rows x 9 columns]

In [0]:
raw_data = pd.read_html("https://www.moneycontrol.com/stocks/marketstats/industry-classification/nse/aquaculture.html")

raw_data

df_nse_aquaculture = raw_data[0]

df_nse_aquaculture = df_nse_aquaculture.drop(columns=['Unnamed: 9','Unnamed: 10','Unnamed: 11','Unnamed: 12','Unnamed: 13','Unnamed: 14','Unnamed: 15','Unnamed: 16','Unnamed: 17','Unnamed: 18','Unnamed: 19'],axis=1)

df_nse_aquaculture = df_nse_aquaculture[0::7][:7:]

df_nse_aquaculture

                                         Company Name  ... 5 Day Performance  5 Day Performance  Volume  Lower Circuit  Upper Circuit  VWAP  SMA 30 DMA  50 DMA  150 DMA  200 DMA  Deliverables  P/E  P/B
0   Ajooni Biotech  Add to  Watchlist | Portfolio ...  ...  AVERAGE VOLUME  5-Day  8800.00  10-Day  30-Day...
7   Apex Frozen  Add to  Watchlist | Portfolio ACT...  ...  AVERAGE VOLUME  5-Day  325245.40  10-Day  3665...
14  Avanti Feeds  Add to  Watchlist | Portfolio AC...  ...  AVERAGE VOLUME  5-Day  1447397.80  10-Day  823...
21  Waterbase  Add to  Watchlist | Portfolio ACTIO...  ...  AVERAGE VOLUME  5-Day  286401.20  10-Day  4736...

[4 rows x 9 columns]

In [0]:
raw_data = pd.read_html("https://www.moneycontrol.com/stocks/marketstats/industry-classification/bse/auto-ancillaries.html")

raw_data

df_bse_auto_ancillaries = raw_data[0]

df_bse_auto_ancillaries = df_bse_auto_ancillaries.drop(columns=['Unnamed: 9','Unnamed: 10','Unnamed: 11','Unnamed: 12','Unnamed: 13','Unnamed: 14','Unnamed: 15','Unnamed: 16','Unnamed: 17','Unnamed: 18','Unnamed: 19'],axis=1)

df_bse_auto_ancillaries = df_bse_auto_ancillaries[0::7][:7:]

df_bse_auto_ancillaries

                                         Company Name  ... 5 Day Performance  5 Day Performance  Volume  Lower Circuit  Upper Circuit  VWAP  SMA 30 DMA  50 DMA  150 DMA  200 DMA  Deliverables  P/E  P/B
0   Enkei Wheels  Add to  Watchlist | Portfolio AC...  ...  AVERAGE VOLUME  5-Day  1948.80  10-Day  1526.2...
7   Frontier Spring  Add to  Watchlist | Portfolio...  ...  AVERAGE VOLUME  5-Day  6537.00  10-Day  7631.6...
14  GNA Axles  Add to  Watchlist | Portfolio ACTIO...  ...  AVERAGE VOLUME  5-Day  15405.00  10-Day  12228...
21  Kinetic Eng  Add to  Watchlist | Portfolio ACT...  ...  AVERAGE VOLUME  5-Day  4176.20  10-Day  5221.7...
28  Pricol  Add to  Watchlist | Portfolio ACTIONS ...  ...  AVERAGE VOLUME  5-Day  169717.60  10-Day  8954...
35  Rajratan Global  Add to  Watchlist | Portfolio...  ...  AVERAGE VOLUME  5-Day  27403.20  10-Day  16987...
42  Rane Brake  Add to  Watchlist | Portfolio ACTI...  ...  AVERAGE VOLUME  5-Day  2236.80  10-Day  1399.2...

[7 rows x 9 columns]

In [0]:
raw_data = pd.read_html("https://www.moneycontrol.com/stocks/marketstats/industry-classification/nse/auto-ancillaries.html")

raw_data

df_nse_auto_ancillaries = raw_data[0]

df_nse_auto_ancillaries = df_nse_auto_ancillaries.drop(columns=['Unnamed: 9','Unnamed: 10','Unnamed: 11','Unnamed: 12','Unnamed: 13','Unnamed: 14','Unnamed: 15','Unnamed: 16','Unnamed: 17','Unnamed: 18','Unnamed: 19'],axis=1)

df_nse_auto_ancillaries = df_nse_auto_ancillaries[0::7][:7:]

df_nse_auto_ancillaries

                                         Company Name  ... 5 Day Performance  5 Day Performance  Volume  Lower Circuit  Upper Circuit  VWAP  SMA 30 DMA  50 DMA  150 DMA  200 DMA  Deliverables  P/E  P/B
0   GNA Axles  Add to  Watchlist | Portfolio ACTIO...  ...  AVERAGE VOLUME  5-Day  70754.00  10-Day  12228...
7   PAE  Add to  Watchlist | Portfolio ANNOUNCEMEN...  ...  AVERAGE VOLUME  5-Day  2588.40  10-Day  808.60...
14  Pricol  Add to  Watchlist | Portfolio ACTIONS ...  ...  AVERAGE VOLUME  5-Day  143803.80  10-Day  8954...
21  Rane Brake  Add to  Watchlist | Portfolio ACTI...  ...  AVERAGE VOLUME  5-Day  19806.40  10-Day  1399....
28  Varroc Engineer  Add to  Watchlist | Portfolio...  ...  AVERAGE VOLUME  5-Day  293370.60  10-Day  1447...

[5 rows x 9 columns]

In [0]:
raw_data = pd.read_html("https://www.moneycontrol.com/stocks/marketstats/industry-classification/bse/auto-ancillaries-air-conditioning-parts.html")

raw_data

df_bse_ac_parts = raw_data[0]

df_bse_ac_parts = df_bse_ac_parts.drop(columns=['Unnamed: 9','Unnamed: 10','Unnamed: 11','Unnamed: 12','Unnamed: 13','Unnamed: 14','Unnamed: 15','Unnamed: 16','Unnamed: 17','Unnamed: 18','Unnamed: 19'],axis=1)

df_bse_ac_parts = df_bse_ac_parts[0::7][:7:]

df_bse_ac_parts

                                        Company Name  ... 5 Day Performance  5 Day Performance  Volume  Lower Circuit  Upper Circuit  VWAP  SMA 30 DMA  50 DMA  150 DMA  200 DMA  Deliverables  P/E  P/B
0  Subros  Add to  Watchlist | Portfolio ACTIONS ...  ...  AVERAGE VOLUME  5-Day  4020.00  10-Day  2689.2...

[1 rows x 9 columns]

In [0]:
raw_data = pd.read_html("https://www.moneycontrol.com/stocks/marketstats/industry-classification/nse/auto-ancillaries-air-conditioning-parts.html")

raw_data

df_nse_ac_parts = raw_data[0]

df_nse_ac_parts = df_nse_ac_parts.drop(columns=['Unnamed: 9','Unnamed: 10','Unnamed: 11','Unnamed: 12','Unnamed: 13','Unnamed: 14','Unnamed: 15','Unnamed: 16','Unnamed: 17','Unnamed: 18','Unnamed: 19'],axis=1)

df_nse_ac_parts = df_nse_ac_parts[0::7][:7:]

df_nse_ac_parts

                                        Company Name  ... 5 Day Performance  5 Day Performance  Volume  Lower Circuit  Upper Circuit  VWAP  SMA 30 DMA  50 DMA  150 DMA  200 DMA  Deliverables  P/E  P/B
0  Subros  Add to  Watchlist | Portfolio ACTIONS ...  ...  AVERAGE VOLUME  5-Day  45724.00  10-Day  2689....

[1 rows x 9 columns]

In [0]:
raw_data = pd.read_html("https://www.moneycontrol.com/stocks/marketstats/industry-classification/nse/auto-ancillaries-auto,-truck-motorcycle-parts.html")

raw_data

df_nse_auto = raw_data[0]

df_nse_auto = df_nse_auto.drop(columns=['Unnamed: 9','Unnamed: 10','Unnamed: 11','Unnamed: 12','Unnamed: 13','Unnamed: 14','Unnamed: 15','Unnamed: 16','Unnamed: 17','Unnamed: 18','Unnamed: 19'],axis=1)

df_nse_auto = df_nse_auto[0::7][:7:]

df_nse_auto

                                         Company Name  ... 5 Day Performance  5 Day Performance  Volume  Lower Circuit  Upper Circuit  VWAP  SMA 30 DMA  50 DMA  150 DMA  200 DMA  Deliverables  P/E  P/B
0   Bosch  Add to  Watchlist | Portfolio ACTIONS  ...  ...  AVERAGE VOLUME  5-Day  35300.60  10-Day  1416....
7   Ind Motor Parts  Add to  Watchlist | Portfolio...  ...  AVERAGE VOLUME  5-Day  2637.80  10-Day  603.40...
14  Mah Scooters  Add to  Watchlist | Portfolio AC...  ...  AVERAGE VOLUME  5-Day  10736.40  10-Day  5251....
21  Motherson Sumi  Add to  Watchlist | Portfolio ...  ...  AVERAGE VOLUME  5-Day  34631549.60  10-Day  11...
28  Sandhar Technol  Add to  Watchlist | Portfolio...  ...  AVERAGE VOLUME  5-Day  13255.00  10-Day  618.3...
35  Sundaram-Clayto  Add to  Watchlist | Portfolio...  ...  AVERAGE VOLUME  5-Day  2818.80  10-Day  120.80...

[6 rows x 9 columns]

In [0]:
raw_data = pd.read_html("https://www.moneycontrol.com/stocks/marketstats/industry-classification/bse/auto-ancillaries-auto,-truck-motorcycle-parts.html")

raw_data

df_bse_auto = raw_data[0]

df_bse_auto = df_bse_auto.drop(columns=['Unnamed: 9','Unnamed: 10','Unnamed: 11','Unnamed: 12','Unnamed: 13','Unnamed: 14','Unnamed: 15','Unnamed: 16','Unnamed: 17','Unnamed: 18','Unnamed: 19'],axis=1)

df_bse_auto = df_bse_auto[0::7][:7:]

df_bse_auto

                                         Company Name  ... 5 Day Performance  5 Day Performance  Volume  Lower Circuit  Upper Circuit  VWAP  SMA 30 DMA  50 DMA  150 DMA  200 DMA  Deliverables  P/E  P/B
0   Bosch  Add to  Watchlist | Portfolio ACTIONS  ...  ...  AVERAGE VOLUME  5-Day  1681.40  10-Day  1416.1...
7   Ind Motor Parts  Add to  Watchlist | Portfolio...  ...  AVERAGE VOLUME  5-Day  1143.20  10-Day  603.40...
14  Mah Scooters  Add to  Watchlist | Portfolio AC...  ...  AVERAGE VOLUME  5-Day  9759.40  10-Day  5251.3...
21  Motherson Sumi  Add to  Watchlist | Portfolio ...  ...  AVERAGE VOLUME  5-Day  1463252.00  10-Day  112...
28  Sandhar Technol  Add to  Watchlist | Portfolio...  ...  AVERAGE VOLUME  5-Day  847.40  10-Day  618.30 ...
35  Sundaram-Clayto  Add to  Watchlist | Portfolio...  ...  AVERAGE VOLUME  5-Day  201.80  10-Day  120.80 ...

[6 rows x 9 columns]

In [0]:
raw_data = pd.read_html("https://www.moneycontrol.com/stocks/marketstats/industry-classification/bse/auto-ancillaries-axle-shafts.html")

raw_data

df_bse_axle = raw_data[0]

df_bse_axle = df_bse_axle.drop(columns=['Unnamed: 9','Unnamed: 10','Unnamed: 11','Unnamed: 12','Unnamed: 13','Unnamed: 14','Unnamed: 15','Unnamed: 16','Unnamed: 17','Unnamed: 18','Unnamed: 19'],axis=1)

df_bse_axle = df_bse_axle[0::7][:7:]

df_bse_axle

                                        Company Name  ... 5 Day Performance  5 Day Performance  Volume  Lower Circuit  Upper Circuit  VWAP  SMA 30 DMA  50 DMA  150 DMA  200 DMA  Deliverables  P/E  P/B
0  Automotive Axle  Add to  Watchlist | Portfolio...  ...  AVERAGE VOLUME  5-Day  1392.20  10-Day  879.70...
7  Talbros Eng  Add to  Watchlist | Portfolio ACT...  ...  AVERAGE VOLUME  5-Day  2684.00  10-Day  1972.0...

[2 rows x 9 columns]

In [0]:
raw_data = pd.read_html("https://www.moneycontrol.com/stocks/marketstats/industry-classification/nse/auto-ancillaries-axle-shafts.html")

raw_data

df_nse_axle = raw_data[0]

df_nse_axle = df_nse_axle.drop(columns=['Unnamed: 9','Unnamed: 10','Unnamed: 11','Unnamed: 12','Unnamed: 13','Unnamed: 14','Unnamed: 15','Unnamed: 16','Unnamed: 17','Unnamed: 18','Unnamed: 19'],axis=1)

df_nse_axle = df_nse_axle[0::7][:7:]

df_nse_axle

                                        Company Name  ... 5 Day Performance  5 Day Performance  Volume  Lower Circuit  Upper Circuit  VWAP  SMA 30 DMA  50 DMA  150 DMA  200 DMA  Deliverables  P/E  P/B
0  Automotive Axle  Add to  Watchlist | Portfolio...  ...  AVERAGE VOLUME  5-Day  16929.20  10-Day  879.7...

[1 rows x 9 columns]

In [0]:
raw_data = pd.read_html("https://www.moneycontrol.com/stocks/marketstats/industry-classification/bse/auto-ancillaries-bearings.html")

raw_data

df_bse_bearings = raw_data[0]

df_bse_bearings = df_bse_bearings.drop(columns=['Unnamed: 9','Unnamed: 10','Unnamed: 11','Unnamed: 12','Unnamed: 13','Unnamed: 14','Unnamed: 15','Unnamed: 16','Unnamed: 17','Unnamed: 18','Unnamed: 19'],axis=1)

df_bse_bearings = df_bse_bearings[0::7][:7:]

df_bse_bearings

                                         Company Name  ... 5 Day Performance  5 Day Performance  Volume  Lower Circuit  Upper Circuit  VWAP  SMA 30 DMA  50 DMA  150 DMA  200 DMA  Deliverables  P/E  P/B
0   Austin Eng  Add to  Watchlist | Portfolio ACTI...  ...  AVERAGE VOLUME  5-Day  871.20  10-Day  932.60 ...
7   Benara Bearings  Add to  Watchlist | Portfolio...  ...        AVERAGE VOLUME  5-Day  10-Day  30-Day  8000
14  Bimetal Bearing  Add to  Watchlist | Portfolio...  ...  AVERAGE VOLUME  5-Day  911.60  10-Day  724.90 ...
21  Galaxy Bearings  Add to  Watchlist | Portfolio...  ...  AVERAGE VOLUME  5-Day  393.20  10-Day  393.70 ...
28  Menon Bearings  Add to  Watchlist | Portfolio ...  ...  AVERAGE VOLUME  5-Day  4350.40  10-Day  3412.2...
35  NRB Bearings  Add to  Watchlist | Portfolio AC...  ...  AVERAGE VOLUME  5-Day  7285.20  10-Day  4784.4...
42  NRB Industrial  Add to  Watchlist | Portfolio ...  ...  AVERAGE VOLUME  5-Day  5484.80  10-Day  6248.7...

[7 rows x 9 columns]

In [0]:
raw_data = pd.read_html("https://www.moneycontrol.com/stocks/marketstats/industry-classification/nse/auto-ancillaries-bearings.html")

raw_data

df_nse_bearings = raw_data[0]

df_nse_bearings = df_nse_bearings.drop(columns=['Unnamed: 9','Unnamed: 10','Unnamed: 11','Unnamed: 12','Unnamed: 13','Unnamed: 14','Unnamed: 15','Unnamed: 16','Unnamed: 17','Unnamed: 18','Unnamed: 19'],axis=1)

df_nse_bearings = df_nse_bearings[0::7][:7:]

df_nse_bearings

                                         Company Name  ... 5 Day Performance  5 Day Performance  Volume  Lower Circuit  Upper Circuit  VWAP  SMA 30 DMA  50 DMA  150 DMA  200 DMA  Deliverables  P/E  P/B
0   Menon Bearings  Add to  Watchlist | Portfolio ...  ...  AVERAGE VOLUME  5-Day  29499.60  10-Day  3412....
7   NRB Bearings  Add to  Watchlist | Portfolio AC...  ...  AVERAGE VOLUME  5-Day  43157.40  10-Day  4784....
14  NRB Industrial  Add to  Watchlist | Portfolio ...  ...  AVERAGE VOLUME  5-Day  7388.60  10-Day  6248.7...
21  Schaeffler Ind  Add to  Watchlist | Portfolio ...  ...  AVERAGE VOLUME  5-Day  11417.80  10-Day  155.3...
28  SKF India  Add to  Watchlist | Portfolio ACTIO...  ...  AVERAGE VOLUME  5-Day  13285.80  10-Day  2825....
35  Timken  Add to  Watchlist | Portfolio ACTIONS ...  ...  AVERAGE VOLUME  5-Day  64334.80  10-Day  2801....

[6 rows x 9 columns]

In [0]:
raw_data = pd.read_html("https://www.moneycontrol.com/stocks/marketstats/industry-classification/bse/auto-ancillaries-brakes.html")

raw_data

df_bse_brakes = raw_data[0]

df_bse_brakes = df_bse_brakes.drop(columns=['Unnamed: 9','Unnamed: 10','Unnamed: 11','Unnamed: 12','Unnamed: 13','Unnamed: 14','Unnamed: 15','Unnamed: 16','Unnamed: 17','Unnamed: 18','Unnamed: 19'],axis=1)

df_bse_brakes = df_bse_brakes[0::7][:7:]

df_bse_brakes

                                        Company Name  ... 5 Day Performance  5 Day Performance  Volume  Lower Circuit  Upper Circuit  VWAP  SMA 30 DMA  50 DMA  150 DMA  200 DMA  Deliverables  P/E  P/B
0  Hind Composites  Add to  Watchlist | Portfolio...  ...  AVERAGE VOLUME  5-Day  483.80  10-Day  2597.40...
7  Sundaram Brake  Add to  Watchlist | Portfolio ...  ...  AVERAGE VOLUME  5-Day  238.80  10-Day  427.80 ...

[2 rows x 9 columns]

In [0]:
raw_data = pd.read_html("https://www.moneycontrol.com/stocks/marketstats/industry-classification/nse/auto-ancillaries-brakes.html")

raw_data

df_nse_brakes = raw_data[0]

df_nse_brakes = df_nse_brakes.drop(columns=['Unnamed: 9','Unnamed: 10','Unnamed: 11','Unnamed: 12','Unnamed: 13','Unnamed: 14','Unnamed: 15','Unnamed: 16','Unnamed: 17','Unnamed: 18','Unnamed: 19'],axis=1)

df_nse_brakes = df_nse_brakes[0::7][:7:]

df_nse_brakes

                                        Company Name  ... 5 Day Performance  5 Day Performance  Volume  Lower Circuit  Upper Circuit  VWAP  SMA 30 DMA  50 DMA  150 DMA  200 DMA  Deliverables  P/E  P/B
0  Hind Composites  Add to  Watchlist | Portfolio...  ...  AVERAGE VOLUME  5-Day  5690.80  10-Day  2597.4...
7  Sundaram Brake  Add to  Watchlist | Portfolio ...  ...  AVERAGE VOLUME  5-Day  3218.00  10-Day  427.80...

[2 rows x 9 columns]

In [0]:
raw_data = pd.read_html("https://www.moneycontrol.com/stocks/marketstats/industry-classification/bse/auto-ancillaries-bus-body.html")

df_bse_bus_body = raw_data[0]

df_bse_bus_body = df_bse_bus_body.drop(columns=['Unnamed: 9','Unnamed: 10','Unnamed: 11','Unnamed: 12','Unnamed: 13','Unnamed: 14','Unnamed: 15','Unnamed: 16','Unnamed: 17','Unnamed: 18','Unnamed: 19'],axis=1)

df_bse_bus_body = df_bse_bus_body[0::7][:7:]

df_bse_bus_body

                                        Company Name  ... 5 Day Performance  5 Day Performance  Volume  Lower Circuit  Upper Circuit  VWAP  SMA 30 DMA  50 DMA  150 DMA  200 DMA  Deliverables  P/E  P/B
0  Auto Corp Goa  Add to  Watchlist | Portfolio A...  ...  AVERAGE VOLUME  5-Day  7747.40  10-Day  4095.6...

[1 rows x 9 columns]

In [0]:
raw_data = pd.read_html("https://www.moneycontrol.com/stocks/marketstats/industry-classification/nse/auto-ancillaries-bus-body.html")

df_nse_bus_body = raw_data[0]

#df_nse_bus_body = df_nse_bus_body.drop(columns=['Unnamed: 9','Unnamed: 10','Unnamed: 11','Unnamed: 12','Unnamed: 13','Unnamed: 14','Unnamed: 15','Unnamed: 16','Unnamed: 17','Unnamed: 18','Unnamed: 19'],axis=1)

df_nse_bus_body = df_nse_bus_body[0::][:7:]

df_nse_bus_body

       Company Name  ... 5 Day Performance  5 Day Performance  Volume  Lower Circuit  Upper Circuit  VWAP  SMA 30 DMA  50 DMA  150 DMA  200 DMA  Deliverables  P/E  P/B
0  No Gainers Today  ...                                                NaN

[1 rows x 9 columns]